# -*- coding: utf-8 -*-
"""LLMExp4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsqEFl4rVTIXhor9sFNHg7CkN-JxgAXW

**Text Classification**
"""

!pip install transformers torch
from transformers import pipeline

# Load pretrained sentiment analysis model
classifier = pipeline("sentiment-analysis")
text = "The online course was extremely helpful and well explained."

result = classifier(text)
print(result)

"""**Named Entity Recognition (NER)**"""

from transformers import pipeline

# Load pretrained NER model
ner = pipeline("ner", aggregation_strategy="simple")

text = "Sundar Pichai is the CEO of Google based in California."

entities = ner(text)
for entity in entities:
    print(entity)

"""**Text Summarization**"""

# Install once if needed
# pip install transformers torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load pretrained summarization model and tokenizer directly
tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

# Input text
text = """
Text summarization is the process of condensing a long piece of text
into a shorter version while preserving the key information and meaning.
It is widely used in news aggregation, search engines, and document analysis.
"""

# Prepare the input for T5 summarization
input_text = "summarize: " + text
inputs = tokenizer(input_text, return_tensors="pt", max_length=512, truncation=True)

# Generate summary
summary_ids = model.generate(
    inputs["input_ids"],
    max_length=50,
    min_length=20,
    num_beams=4,
    early_stopping=True
)
summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Summary:", summary_text)

"""**Question Answering (QA)**"""

from transformers import pipeline

qa = pipeline("question-answering")

context = """
Transformers are deep learning models introduced by Google.
They are widely used in NLP tasks like translation and summarization.
"""

question = "Who introduced Transformers?"

answer = qa(question=question, context=context)
print(answer)

"""**Text Classification for Encoder**"""

!pip install transformers torch

from transformers import pipeline

# Load encoder-only model
classifier = pipeline("sentiment-analysis", model="bert-base-uncased")

text = "The course content was very informative and easy to understand."

result = classifier(text)
print(result)

"""**Text calssification for Decoder**"""

!pip install transformers torch

from transformers import pipeline

classifier = pipeline(
    "text-generation",
    model="gpt2"
)

prompt = """
Classify the sentiment of the following text as Positive or Negative.
Text: "The product quality is excellent and reliable."
Sentiment:
"""

output = classifier(prompt, max_length=50)
print(output[0]["generated_text"])

"""**Text Classification for Encoder+Decoder using T5**"""

!pip install transformers torch

from transformers import pipeline

classifier = pipeline(
    "text2text-generation",
    model="t5-small"
)

text = "The service was extremely slow and disappointing."

input_text = "classify sentiment: " + text

result = classifier(input_text)
print(result[0]["generated_text"])