# -*- coding: utf-8 -*-
"""LLM exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixNxz3ptg4tTt6cbjRcYrkIZlr40Dxye
"""

from transformers import pipeline

sentiment_analyzer = pipeline("sentiment-analysis")

text = "I am a bad student"

result = sentiment_analyzer(text)

print(result)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
texts = [
    "Government announces new policy",
    "Aliens landed on earth yesterday"
]
labels = [1, 0]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)
model = LogisticRegression()
model.fit(X, labels)
test_news = ["Aliens are controlling humans"]
test_vec = vectorizer.transform(test_news)
prediction = model.predict(test_vec)
print("Prediction:", "Real News" if prediction[0] == 1 else "Fake News")

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)

text = "I am very happy with the service"


inputs = tokenizer(text, return_tensors="pt")


with torch.no_grad():
    outputs = model(**inputs)

label = torch.argmax(outputs.logits).item()
print("Sentiment:", "POSITIVE" if label == 1 else "NEGATIVE")