# -*- coding: utf-8 -*-
"""LLM exp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vhQGYMTMc86CbKojGfbn2JCH6GB39ct
"""

import torch
import torch.nn.functional as F
import math

# batch_size = 1, sequence_length = 3, embedding_dimension = 4
X = torch.tensor([
    [[1.0, 0.0, 1.0, 0.0],
     [0.0, 2.0, 0.0, 2.0],
     [1.0, 1.0, 1.0, 1.0]]
])


W_Q = torch.rand(4, 4)
W_K = torch.rand(4, 4)
W_V = torch.rand(4, 4)


Q = X @ W_Q   # Query
K = X @ W_K   # Key
V = X @ W_V   # Value


# Formula: QKᵀ / √dₖ
attention_scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(K.size(-1))

# Softmax normalization
attention_weights = F.softmax(attention_scores, dim=-1)

# Weighted sum of Value vectors
context_vector = torch.matmul(attention_weights, V)

# Step 6: Print Everything

print(" Input X:\n", X)
print("\n Query (Q):\n", Q)
print("\n Key (K):\n", K)
print("\n Value (V):\n", V)

print("\n Attention Scores:\n", attention_scores)
print("\n Attention Weights (Softmax):\n", attention_weights)

print("\n Context Vector (Final Output):\n", context_vector)