# -*- coding: utf-8 -*-
"""TOEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BT9I7aAO5aIThduiAUWsCA7sVzisOlaL

**`Tokenization Using Whitespace`**
"""

text = "Tokenization using whitespace is simple"

# Whitespace tokenization
tokens = text.split()

print(tokens)

"""**`Tokenization Using sub-word`**"""

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

text = "Electroencephalography measures brain activity."

tokens = tokenizer.tokenize(text)

print("Subword Tokens:", tokens)

"""**`Tokenization Using stop-words`**"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download required NLTK data (only once)
nltk.download('punkt')
nltk.download('stopwords')

text = "Natural Language Processing is useful for analyzing text data."

# Tokenization
tokens = word_tokenize(text)

# Stop words list
stop_words = set(stopwords.words('english'))

# Remove stop words
filtered_tokens = [token for token in tokens if token.lower() not in stop_words]

print("Tokens:", tokens)
print("Filtered Tokens:", filtered_tokens)

"""**`character level tokenization`**"""

text = "I love my Father"

# Character level tokenization
tokens = list(text)

print(tokens)

"""**`Tokenization using NLP library`**"""

import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

text = "Tokenization using NLP libraries is easy."

tokens = word_tokenize(text)
print(tokens)

"""**`Sentence and Word Tokenization`**"""

import nltk
from nltk.tokenize import sent_tokenize

nltk.download('punkt')

text = "AI is changing the world. It can write code, answer questions, and help in education."

sentences = sent_tokenize(text)
print(sentences)

"""**`one hot embedding`**"""

from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Example categories
data = np.array(["Every", "moment", "is", "a","beginning"]).reshape(-1, 1)

encoder = OneHotEncoder(sparse_output=False) # Changed 'sparse' to 'sparse_output'
one_hot = encoder.fit_transform(data)

print(one_hot)

"""**`Bag Of Words embedding`**"""

from sklearn.feature_extraction.text import CountVectorizer

# Example documents
documents = [
    "I love NLP",
    "NLP is interesting",
    "I love machine learning"
]

# Create BoW model
vectorizer = CountVectorizer()

# Fit the model and transform the documents
bow_matrix = vectorizer.fit_transform(documents)

# Convert sparse matrix to array
bow_array = bow_matrix.toarray()

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Vectors:\n", bow_array)

"""**`Wordvec Embedding`**"""

!pip install gensim
from gensim.models import Word2Vec

# Example sentences (tokenized)
sentences = [
    ["i", "love", "nlp"],
    ["nlp", "is", "fun"],
    ["i", "love", "learning"]
]

# Train Word2Vec model
model = Word2Vec(sentences, vector_size=50, min_count=1)

# Get embedding for a word
print(model.wv["nlp"])

"""**`Glove Embedding`**"""

!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

import numpy as np

# Load GloVe embeddings
def load_glove(file_path):
    embeddings = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.asarray(values[1:], dtype='float32')
            embeddings[word] = vector
    return embeddings

# Example: using glove.6B.100d.txt
glove_path = "glove.6B.100d.txt"
glove_embeddings = load_glove(glove_path)

# Function to get sentence embedding
def sentence_embedding(sentence, embeddings):
    words = sentence.lower().split()
    vectors = [embeddings[word] for word in words if word in embeddings]

    if len(vectors) == 0:
        return None

    # Average all word vectors
    return np.mean(vectors, axis=0)

# New sentence
sentence = "Deep learning is transforming the world of technology."

sent_vec = sentence_embedding(sentence, glove_embeddings)

print("Sentence Embedding Vector:\n", sent_vec)
print("Vector Shape:", sent_vec.shape)

"""**`BERT embedding`**"""

from transformers import BertModel, BertTokenizer
import torch

# Load pre-trained BERT model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Example text
text = "Natural language processing is amazing."

# Tokenize the text
inputs = tokenizer(text, return_tensors='pt')

# Get model output
outputs = model(**inputs)

# Get embeddings (last hidden state)
embeddings = outputs.last_hidden_state

print(embeddings.shape)